apiVersion: v2
name: hull
description: A general-purpose Helm chart for deploying applications to Kubernetes. Convention over configuration, no footguns.
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - app-template
  - homelab
  - gitops
  - general-purpose
home: https://github.com/Kampe/hull
icon: https://github.com/kampe.png
sources:
  - https://github.com/Kampe/hull
maintainers:
  - name: kampe
    url: https://github.com/Kampe
