{{- $fullname := include "hull.fullname" . -}}
{{- $labels := include "hull.labels" . -}}
{{- range $name, $cm := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-{{ $name }}
  labels:
    {{- $labels | nindent 4 }}
data:
  {{- range $key, $value := $cm.data }}
  {{- if kindIs "string" $value }}
  {{- if contains "\n" $value }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- else }}
  {{ $key }}: |
    {{- toYaml $value | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
